# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('idBook', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('datePublished', models.DateField(max_length=10)),
                ('numberOfPages', models.IntegerField()),
                ('typeOfBook', models.CharField(max_length=50)),
            ],
        ),
    ]
